### ISSUE TITLE
No link from npmjs to GitHub

### ISSUE THREAD

**Issue by patarapolw** [Sujimoshi/jsonschema-definer#10]
That is, I cannot click directly from <https://www.npmjs.com/package/jsonschema-definer> to <https://github.com/Sujimoshi/jsonschema-definer>.

I believe you have to define several things in `package.json`, e.g.

```json
{
  "repository": "Sujimoshi/jsonschema-definer",
}
```

and possibly `readme` and `homepage` as well.

Yes, I am here to give a 🌟 .

**Comment by Sujimoshi** [comment]
Thanks
