### ISSUE TITLE
Can we define a schema which is a union of other schemas?

### ISSUE THREAD

**Issue by asnaseer-resilient** [Sujimoshi/jsonschema-definer#15]
How would I define a schema that allowed any of the following two JSON input objects:
```
{
  playMenu: { audio: "prompt.wav" }
}
```
```
{
  terminate: { reason: "busy" }
}
```

**Comment by Sujimoshi** [comment]
@asnaseer-resilient try this:
`S.anyOf(S.shape({ playMenu ... }), S.shape({ terminate ...}))`
