### ISSUE TITLE
Curry function not usable for custom validators

### ISSUE THREAD

**Issue by simonkarman** [Sujimoshi/jsonschema-definer#16]
When you have multiple similar validation requirements in you schema, then using a curry function for these variants of the same validation steps can be a nice approach.

```ts
function isFormattedDateTime(format: string) {
  return (value: unknown, format: string, path: string) => {
    if (typeof value === 'string' && moment(value, format, true).isValid()) {
      return true;
    }
    throw new Error(`The value of '${path}' is not a date time formatted as '${format}',`
        + ` instead its value is '${value}'.`);
  };
}

// Usage
S.schema({
  niceDateTime: S.string().custom(isFormattedDateTime('YYYY-MM-DD HH:mm')),
  anotherDifferentDateTime: S.string().custom(isFormattedDateTime('YYYY-MM-DD HH:mm:ss.SSSZ'))
)}
```

When adding custom validation this library internally creates a md5 hash of the function body. This md5 is later used to reference it. Since all the variants of the curry function result in the same md5, I found that only the last used curry parameters will be used during validation. **This is not correct, and the above example should be used with caution because it results in unexpected behaviour**.

The following approach does work. For this you need to define a separate function for each possible option. This can be quite cumbersome when working with many different variants.
```ts
function isFormattedDateTime(value: unknown, format: string, path: string) {
  if (typeof value === 'string' && moment(value, format, true).isValid()) {
    return true;
  }
  throw new Error(`The value of '${path}' is not a date time formatted as '${format}',`
      + ` instead its value is '${value}'.`);
}

export function isNanoPrecisionDateTime(value: unknown, _: unknown, __: unknown, path: string) {
  return isFormattedDateTime(value, 'YYYY-MM-DDTHH:mm:ss.SSSZ', path);
}

export function isMinutePrecisionDateTime(value: unknown, _: unknown, __: unknown, path: string) {
  return isFormattedDateTime(value, 'YYYY-MM-DDTHH:mm', path);
}

// Usage
S.schema({
  niceDateTime: S.string().custom(isMinutePrecisionDateTime),
  anotherDifferentDateTime: S.string().custom(isNanoPrecisionDateTime)
)}
```

This problem is hard to find and it should either be explicitly stated as a limitation of using this library, or an internal change should be made to allow curried custom validation functions.

**Comment by Sujimoshi** [comment]
@simonkarman Nice work. I should think about better approach for custom validators mapping

**Comment by Sujimoshi** [comment]
https://github.com/Sujimoshi/jsonschema-definer/blob/master/src/base.ts#L311
I think we need another approach for this.
Something like this:
```ts
custom (...validators: Validator[]) {
    const keys = validators.map(validator => {
      const hash = uuid()
      BaseSchema.validators[hash] = validator
      return hash
    })
    return this.copyWith({ plain: { custom: [...this.plain.custom || [], ...keys] } })
  }
```

**Comment by Sujimoshi** [comment]
Fixed
